# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Slz\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 10, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 90, 771, 441))
        self.listView.setObjectName("listView")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 10, 461, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 691, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuRedis = QtWidgets.QMenu(self.menubar)
        self.menuRedis.setObjectName("menuRedis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_action = QtWidgets.QAction(MainWindow)
        self.menu_action.setCheckable(False)
        self.menu_action.setObjectName('menuAction')
        self.menubar.addAction(self.menu_action)
        self.menu_Redis_action = QtWidgets.QAction(MainWindow)
        self.menu_Redis_action.setCheckable(False)
        self.menu_Redis_action.setObjectName('menuRedisAction')
        self.menubar.addAction(self.menu_Redis_action)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KittyScan"))
        self.pushButton.setText(_translate("MainWindow", "扫描"))
        self.pushButton_2.setText(_translate("MainWindow", "打开Kitty添加设备页面"))
        self.menu_action.setText(_translate("MainWindow", "关于"))
        self.menu_Redis_action.setText(_translate("MainWindow", "Redis设置"))
        self.label.setText(_translate("MainWindow", "IP地址范围："))
        self.lineEdit.setText(_translate("MainWindow", "192.168.2.1-254"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menuRedis.setTitle(_translate("MainWindow", "Redis设置"))
